import { test, expect } from '@playwright/test';
import { openApp, waitForHydration } from './helpers';

test('overlay controls work with keyboard and touch and theme changes sync between windows', async ({ page, context }, info) => {
	test.setTimeout(90_000);
	await openApp(page);
	await page.goto('/app/settings/display');
	const overlay = await context.newPage();
	await overlay.goto('/overlay');
	await waitForHydration(overlay);
	await page.getByRole('group', { name: 'Color theme' }).getByRole('button', { name: 'Dark', exact: true }).click();
	await expect(overlay.locator('html')).toHaveClass(/dark/);
	await expect(overlay.locator('.overlay-app')).toHaveCSS('background-color', 'rgba(0, 0, 0, 0)');
	const camera = overlay.getByRole('button', { name: 'Camera settings', exact: true });
	await camera.focus();
	await expect(camera).toHaveCSS('opacity', '1');
	await camera.press('Enter');
	await expect(overlay.locator('.camera-panel')).toBeVisible();
	await overlay.keyboard.press('Escape');
	await expect(overlay.locator('.camera-panel')).toHaveCount(0);
	await expect(camera).toBeFocused();
	const lock = overlay.getByRole('button', { name: 'Lock position', exact: true });
	await lock.focus();
	await lock.press('Enter');
	await expect(overlay.getByRole('button', { name: 'Unlock position', exact: true })).toHaveAttribute('aria-pressed', 'true');
	await overlay.reload();
	await waitForHydration(overlay);
	await expect(overlay.getByRole('button', { name: 'Unlock position', exact: true })).toHaveAttribute('aria-pressed', 'true');
	await overlay.getByRole('button', { name: 'Open chat', exact: true }).click();
	const input = overlay.getByRole('textbox', { name: 'Message', exact: true });
	await input.fill('Keep my overlay draft');
	await input.press('Escape');
	await expect(input).toHaveCount(0);
	await expect(overlay.getByRole('button', { name: 'Open chat', exact: true })).toBeFocused();
	await overlay.getByRole('button', { name: 'Open chat', exact: true }).click();
	await expect(input).toHaveValue('Keep my overlay draft');
	await overlay.getByRole('button', { name: 'Collapse chat', exact: true }).click();
	await overlay.getByRole('button', { name: 'Companion stats', exact: true }).click();
	const stats = overlay.getByRole('dialog', { name: 'Companion stats' });
	await expect(stats.locator('.companion-state-summary')).toBeVisible();
	await overlay.screenshot({ path: info.outputPath('overlay-stats-dark.png') });
	await stats.getByRole('link', { name: 'Character settings' }).click();
	await expect(overlay).toHaveURL(/app\/settings\/persona\?view=state$/);
	expect(await overlay.locator('body').evaluate(el => el.style.background)).toBe('');
	await overlay.close();
});
